#!/usr/bin/env bash
# Displays "Best School" ten times except on the 4th ("bad luck") and the 8th ("good luck")
i=0

while (( i < 10 ))
do
	if (( i == 3 ))
	then
		echo "bad luck"
	elif (( i == 7 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	(( i++ ))
done	
