#!/usr/bin/env bash
#Display numbers from 1 to 20, with 
# "bad luck from China" behind 4
# "bad luck from Japan" behind 9
# "bad luck from Italy" behind 17
i=0

while (( i < 20 ))
do
	(( i++ ))

	case $i in
		4)
			echo $i
			echo "bad luck from China"
			;;
		
		9)
			echo $i
			echo "bad luck from Japan"
			;;

		17)
			echo $i
			echo "bad luck from Italy"
			;;

		*)
			echo $i
	esac
done
