#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" when receiving a SIGTERM signal
# Displays "Y U no love me?!" when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
pgrep -f 10-process_and_pid_file > myscript.pid
sudo mv myscript.pid /var/run/

while true
do
	trap "echo Y U no love me ?!" SIGINT
	trap "sudo rm /var/run/myscript.pid; pkill -SIGKILL -f 10-process_and_pid_file" SIGQUIT
	trap "echo 'I hate the kill command'; sudo rm /var/run/myscript.pid; pkill -SIGKILL -f 10-process_and_pid_file" SIGTERM

	echo "To infinity and beyond"
done
