#!/usr/bin/env bash
# Init script to manage manage_my_process
if [[ $1 = "start" ]]
then
	./manage_my_process &
	pgrep -f manage_my_process > my_process.pid
	sudo mv my_process.pid /var/run/
	echo "manage_my_process started"
elif [[ $1 = "stop"  ]]
then
	echo "manage_my_process stopped"
	pkill -f manage_my_process
	rm /var/run/my_process.pid
elif [[ $1 = "restart"  ]]
then
	echo "manage_my_process restarted"
	pkill -f manage_my_process
	sudo rm /var/run/my_process.pid
	./manage_my_process &
	pgrep -f manage_my_process > my_process.pid
	sudo mv my_process.pid /var/run/
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
